@startuml

!include style.iuml
!include drawpool.iuml


$DrawPool("Pool", 0)
$DrawPool("Merging Pool", 1)
$DrawPool("Decomissioning Pool", 2)
$DrawPool("Unallocated", 3)



node12 ---> node18
node13 ---> node19
node14 ---> node20
node15 ---> node21
node16 ---> node22
node17 ---> node23

pool2 --|> pool1 : merge data

pool0 -[hidden]-- pool1
pool0 -[hidden]-- pool2
pool2 -[hidden]-- pool3
pool1 -[hidden]-- pool3




@enduml
